#spring:
#  application:
#    name: intervai
#  ai:
#    anthropic:
#      api-key: ${ANTHROPIC_API_KEY:}
#      chat:
#        options:
#          model: claude-sonnet-4-20250514
#          max-tokens: 1024
#  jpa:
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#
#jwt:
#  access:
#    secret: ${JWT_ACCESS_SECRET:defaultAccessSecretKeyForLocalDevelopmentOnlyDoNotUse1234567890}
#    expiration: 86400000
#  refresh:
#    secret: ${JWT_REFRESH_SECRET:defaultRefreshSecretKeyForLocalDevelopmentOnlyDoNotUse123456789}
#    expiration: 604800000
spring:
  profiles:
    active: local
