server:
  port: ${SERVER_PORT:8080}

spring:
  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${API_KEY}
        chat:
          options:
            model: ${MODEL:gemini-3-flash-preview}
            response-mime-type: application/json
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false

app:
  cors:
    prod-allowed-origins: ${APP_CORS_PROD_ALLOWED_ORIGINS:http://localhost:5173}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:defaultAccessSecretKeyForLocalDevelopmentOnlyDoNotUse1234567890}
    expiration: 86400000
  refresh:
    secret: ${JWT_REFRESH_SECRET:defaultRefreshSecretKeyForLocalDevelopmentOnlyDoNotUse123456789}
    expiration: 604800000
