spring:
  ai:
    anthropic:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6370
  datasource:
    url: jdbc:h2:mem:intervai
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
